[package]
name = "lf_modapi"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = { version = "0.8", default-features = false, features = ["parse", "display"] }
lf_voxel = { path = "../lf_voxel" }
lf_game = { path = "../lf_game" }
lf_worldgen = { path = "../lf_worldgen" }
tempfile = "3.10"
lf_assets = { path = "../lf_assets" }
