[package]
name = "lf_vistest"
version = "0.1.0"
edition = "2021"

[dependencies]
lf_engine = { path = "../lf_engine" }
lf_voxel = { path = "../lf_voxel" }
lf_worldgen = { path = "../lf_worldgen" }
lf_assets = { path = "../lf_assets" }
glam = "0.30"
image = { version = "0.25", default-features = false, features = ["png"] }
