//! N05 (nightly-beta `04-WORLDGEN-SEEDS-AND-BIOMES`): the canonical
//! world identity and the seed-text rules. One struct answers "what world
//! is this?" across creation, saves, multiplayer Welcome, and the seed
//! laboratory — same identity, same world; different seed, provably
//! different world (see `seedlab`).

use crate::WorldType;

pub const IDENTITY_FILE: &str = "identity.dat";

/// The canonical identity of a generated world. `seed_u64` alone names a
/// world only for one generator version and mod set; the full tuple is
/// what determinism promises to reproduce.
#[derive(Clone, Copy, Debug, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct WorldIdentity {
    pub seed_u64: u64,
    pub generator_version: u32,
    pub world_type: WorldType,
    /// Fingerprint of everything modded that can alter generation
    /// (registered mod recipes + ore hooks). 0 = vanilla.
    pub mod_fingerprint: u64,
}

impl WorldIdentity {
    /// The identity a freshly created world stamps for itself.
    pub fn new(seed: u64, world_type: WorldType, mod_fingerprint: u64) -> Self {
        Self {
            seed_u64: seed,
            generator_version: crate::GENERATOR_VERSION,
            world_type,
            mod_fingerprint,
        }
    }

    /// Persist into a world directory (JSON, self-describing for future
    /// fields). Written BEFORE generation begins, per the seed contract.
    pub fn save(&self, dir: &std::path::Path) -> std::io::Result<()> {
        std::fs::create_dir_all(dir)?;
        std::fs::write(dir.join(IDENTITY_FILE), serde_json::to_vec_pretty(self).unwrap_or_default())
    }

    /// Read the identity a world was created with. Falls back field by
    /// field (legacy saves predate identity.dat): the seed from
    /// seed.dat, the version stamp from genver.dat (None = unstamped
    /// pre-P25), mod fingerprint 0.
    pub fn load(dir: &std::path::Path, fallback_seed: u64, world_type: WorldType)
        -> std::io::Result<Self> {
        if let Ok(bytes) = std::fs::read(dir.join(IDENTITY_FILE)) {
            if let Ok(id) = serde_json::from_slice::<WorldIdentity>(&bytes) {
                return Ok(id);
            }
        }
        Ok(Self {
            seed_u64: fallback_seed,
            generator_version: crate::load_generator_version(dir).unwrap_or(0),
            world_type,
            mod_fingerprint: 0,
        })
    }

    /// A documented salted channel derived from the FULL 64-bit seed —
    /// never a shared truncation. Feature families salt differently so
    /// knowing one channel's output never pins another's.
    pub fn channel(&self, salt: u64) -> i32 {
        crate::channel_seed_pub(self.seed_u64, salt)
    }

    /// The one-line form players reason about ("seed 12345 · gen v6 ·
    /// Normal · vanilla" / "… · 3 mods").
    pub fn describe(&self) -> String {
        format!(
            "seed {} · gen v{} · {:?} · {}",
            self.seed_u64,
            self.generator_version,
            self.world_type,
            if self.mod_fingerprint == 0 { "vanilla".to_string() }
            else { format!("mods #{:016x}", self.mod_fingerprint) }
        )
    }
}

/// Hash a non-numeric world-seed string to a u64. Stable across runs and
/// machines (std's DefaultHasher is NOT — its keys are randomized), so a
/// shared seed string always builds the same world.
pub fn hash_seed_string(s: &str) -> u64 {
    // FNV-1a 64 over the UTF-8 bytes, then splitmix-mixed for good spread.
    let mut h: u64 = 0xcbf29ce484222325;
    for b in s.as_bytes() {
        h ^= *b as u64;
        h = h.wrapping_mul(0x100000001b3);
    }
    let mut z = h;
    z = (z ^ (z >> 30)).wrapping_mul(0xBF58476D1CE4E5B9);
    z = (z ^ (z >> 27)).wrapping_mul(0x94D049BB133111EB);
    z ^ (z >> 31)
}

/// Parse the seed field the way the seed contract demands: numeric text
/// is the number (u64, exact); word text hashes stably; EMPTY means "roll
/// one" and the caller writes the rolled value into slot metadata before
/// generation. `random` is injected so tests stay deterministic.
pub fn parse_seed_text(raw: &str, random: impl FnOnce() -> u64) -> u64 {
    let s = raw.trim();
    if let Ok(v) = s.parse::<u64>() {
        return v;
    }
    if s.is_empty() {
        random()
    } else {
        hash_seed_string(s)
    }
}

/// Explicit generator-version mismatch policy. Saves older than the
/// current generator regenerate unedited chunks with the NEW generator —
/// allowed, but it must be a decision this enum names, not an accident.
/// Edited chunks are persisted and never regenerated.
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum VersionMismatch {
    /// The save was generated by the running generator.
    Current,
    /// Regenerated chunks may differ from their first visit. `saved` is
    /// None for unstamped pre-P25 worlds.
    Legacy { saved: Option<u32> },
}

pub fn version_check(stamped: Option<u32>) -> VersionMismatch {
    match stamped {
        Some(v) if v == crate::GENERATOR_VERSION => VersionMismatch::Current,
        saved => VersionMismatch::Legacy { saved },
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn seed_text_rules() {
        // numeric seeds parse exactly, u64 boundary included
        assert_eq!(parse_seed_text("123", || panic!("must not roll")), 123);
        assert_eq!(parse_seed_text("  12345  ", || panic!()), 12345);
        assert_eq!(parse_seed_text(&u64::MAX.to_string(), || panic!()), u64::MAX);
        // word seeds hash stably (same text, same world — always)
        assert_eq!(parse_seed_text("valdenmoor", || panic!()),
            parse_seed_text("  valdenmoor ", || panic!()));
        assert_ne!(parse_seed_text("valdenmoor", || panic!()),
            parse_seed_text("valdenmoors", || panic!()));
        // numeric and word namespaces cannot collide by accident for a
        // known pair (hash of "123" is not 123)
        assert_ne!(parse_seed_text("123", || panic!()), hash_seed_string("123"));
        // empty rolls exactly once and the caller persists the result
        assert_eq!(parse_seed_text("", || 777), 777);
    }

    #[test]
    fn hash_is_stable_and_spread() {
        // golden stability: any change to this hash breaks every shared
        // word seed — the test makes that a deliberate act
        assert_eq!(hash_seed_string("valdenmoor"), {
            let mut h: u64 = 0xcbf29ce484222325;
            for b in b"valdenmoor" {
                h ^= *b as u64;
                h = h.wrapping_mul(0x100000001b3);
            }
            let mut z = h;
            z = (z ^ (z >> 30)).wrapping_mul(0xBF58476D1CE4E5B9);
            z = (z ^ (z >> 27)).wrapping_mul(0x94D049BB133111EB);
            z ^ (z >> 31)
        });
        // small text differences spread across the full u64 space
        let a = hash_seed_string("a");
        let b = hash_seed_string("b");
        assert!(a.leading_zeros() + b.leading_zeros() < 40 || a != b, "poor spread");
    }

    #[test]
    fn identity_round_trips_through_disk() {
        let dir = tempfile::tempdir().unwrap();
        let id = WorldIdentity::new(12345, WorldType::Amplified, 0xABCD);
        id.save(dir.path()).unwrap();
        let back = WorldIdentity::load(dir.path(), 999, WorldType::Normal).unwrap();
        assert_eq!(back, id, "saved identity wins over fallbacks");
        // legacy dir (no identity.dat): falls back to seed.dat value + no
        // version stamp
        let dir2 = tempfile::tempdir().unwrap();
        let legacy = WorldIdentity::load(dir2.path(), 48291, WorldType::Normal).unwrap();
        assert_eq!(legacy.seed_u64, 48291);
        assert_eq!(legacy.generator_version, 0, "unstamped pre-P25 reads as 0");
        assert_eq!(legacy.mod_fingerprint, 0);
    }

    #[test]
    fn version_policy_is_explicit() {
        assert_eq!(version_check(Some(crate::GENERATOR_VERSION)), VersionMismatch::Current);
        assert_eq!(version_check(None), VersionMismatch::Legacy { saved: None });
        assert_eq!(version_check(Some(1)), VersionMismatch::Legacy { saved: Some(1) });
    }

    #[test]
    fn channels_salt_and_never_truncate_together() {
        let id = WorldIdentity::new(0xFFFF_FFFF_FFFF_FFFF, WorldType::Normal, 0);
        // distinct salts give decorrelated channels
        let a = id.channel(1);
        let b = id.channel(2);
        assert_ne!(a, b);
        // the full 64-bit seed matters: adjacent seeds diverge on channel 7
        let near = WorldIdentity::new(id.seed_u64.wrapping_add(1), WorldType::Normal, 0);
        assert_ne!(id.channel(7), near.channel(7));
        // describe reads like a player line
        let d = id.describe();
        assert!(d.contains("seed 18446744073709551615"), "{d}");
        assert!(d.contains("vanilla"), "{d}");
    }
}
